"""empty message

Revision ID: 98185df87adc
Revises: 
Create Date: 2023-06-10 14:52:45.496186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98185df87adc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('desc', sa.VARCHAR(length=200), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
