"""empty message

Revision ID: c0e0cee3f1ce
Revises: 98185df87adc
Create Date: 2023-06-10 18:19:37.870608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0e0cee3f1ce'
down_revision = '98185df87adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adopted', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['adopted'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('adopted')

    # ### end Alembic commands ###
